spring:

  datasource:
    url: jdbc:mysql://localhost:3306/dev?serverTimezone=UTC
    username: root
    password: Wy20001976
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1


# 开启mp控制
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl